use crate::models::{ConsolidationStatus, PairVerificationResult, VerificationReceipt};
use std::fmt::Write;

/// Generates a GitHub-flavored Markdown receipt from verification results.
pub fn generate_markdown_receipt(receipt: &VerificationReceipt) -> String {
    let mut md = String::with_capacity(1024 + (receipt.pairs.len() * 256));

    render_header(&mut md, receipt);
    render_status_banner(&mut md, receipt);
    render_summary_metrics(&mut md, receipt);
    render_fee_exemption_audit(&mut md, receipt);
    render_pairs_table(&mut md, &receipt.pairs);

    let _ = write!(
        md,
        "\n---\n*Generated by `stvault-receipt` v{} (Lido stVault Consolidation Verifier)*\n",
        receipt.tool_version
    );

    md
}

// -----------------------------------------------------------------------------
// Section Renderers
// -----------------------------------------------------------------------------

fn render_header(md: &mut String, receipt: &VerificationReceipt) {
    let _ = writeln!(md, "# Lido stVault Consolidation Request Receipt\n");
    let _ = writeln!(md, "**Generated At:** {}", receipt.timestamp.to_rfc3339());
    let _ = writeln!(md, "**CLI Tool Version:** v{}", receipt.tool_version);
    let _ = writeln!(md, "**Execution Layer RPC:** `{}`", receipt.el_rpc_url);
    let _ = writeln!(
        md,
        "**Consensus Beacon API:** `{}`\n",
        receipt.cl_beacon_url
    );
}

fn render_status_banner(md: &mut String, receipt: &VerificationReceipt) {
    let is_all_accepted =
        receipt.summary.accepted == receipt.summary.total_pairs && receipt.summary.total_pairs > 0;

    if is_all_accepted {
        let _ = writeln!(md, "> [!NOTE]");
        let _ = writeln!(md, "> **STATUS: ALL CONSOLIDATION REQUESTS ACCEPTED**");
        let _ = writeln!(
            md,
            "> All consolidation pairs have been verified in the Consensus Layer pending queue.\n"
        );
    } else if receipt.summary.not_accepted > 0 || receipt.summary.indeterminate > 0 {
        let _ = writeln!(md, "> [!WARNING]");
        let _ = writeln!(md, "> **STATUS: ATTENTION REQUIRED**");
        let _ = writeln!(
            md,
            "> One or more consolidation requests were NOT accepted or returned INDETERMINATE."
        );
        let _ = writeln!(
            md,
            "> Do NOT decommission source validator hardware until all pairs are verified.\n"
        );
    }
}

fn render_summary_metrics(md: &mut String, receipt: &VerificationReceipt) {
    let _ = writeln!(md, "## 1. Summary Metrics\n");
    let _ = writeln!(md, "| Metric | Count | Percentage |");
    let _ = writeln!(md, "| :--- | :--- | :--- |");

    let total = receipt.summary.total_pairs;
    let pct = |count: usize| {
        if total > 0 {
            (count as f64 / total as f64) * 100.0
        } else {
            0.0
        }
    };

    let _ = writeln!(md, "| **Total Validator Pairs** | `{}` | `100.0%` |", total);
    let _ = writeln!(
        md,
        "| **Accepted (In CL Pending Queue)** | `{}` | `{:.1}%` |",
        receipt.summary.accepted,
        pct(receipt.summary.accepted)
    );
    let _ = writeln!(
        md,
        "| **Queued (Awaiting CL State)** | `{}` | `{:.1}%` |",
        receipt.summary.queued,
        pct(receipt.summary.queued)
    );
    let _ = writeln!(
        md,
        "| **Not Accepted / Dropped** | `{}` | `{:.1}%` |",
        receipt.summary.not_accepted,
        pct(receipt.summary.not_accepted)
    );
    let _ = writeln!(
        md,
        "| **Indeterminate / Unverified** | `{}` | `{:.1}%` |\n",
        receipt.summary.indeterminate,
        pct(receipt.summary.indeterminate)
    );
}

fn render_fee_exemption_audit(md: &mut String, receipt: &VerificationReceipt) {
    let _ = writeln!(md, "## 2. Lido Fee-Exemption Role Audit\n");
    let _ = writeln!(
        md,
        "- **stVault Dashboard / ACL:** `{}`",
        receipt
            .fee_exemption
            .st_vault_dashboard
            .as_deref()
            .unwrap_or("N/A")
    );
    let _ = writeln!(
        md,
        "- **Operator Address:** `{}`",
        receipt
            .fee_exemption
            .operator_address
            .as_deref()
            .unwrap_or("N/A")
    );
    let _ = writeln!(
        md,
        "- **`NODE_OPERATOR_FEE_EXEMPT_ROLE` Hash:** `{}`",
        receipt.fee_exemption.role_hash
    );

    let role_status_str = match receipt.fee_exemption.role_active {
        Some(true) => "⚠️ ACTIVE (Elevated privilege active)",
        Some(false) => "✅ INACTIVE (Revoked or clean)",
        None => "ℹ️ UNCHECKED / NOT PROVIDED",
    };
    let _ = writeln!(md, "- **Current Role State:** {}", role_status_str);
    let _ = writeln!(md, "- **Audit Notes:** {}\n", receipt.fee_exemption.notes);
}

fn render_pairs_table(md: &mut String, pairs: &[PairVerificationResult]) {
    let _ = writeln!(md, "## 3. Pair-by-Pair Consolidation Verification\n");
    let _ = writeln!(
        md,
        "| # | Source Validator | Target Validator | EL Tx Hash | Status | Details |"
    );
    let _ = writeln!(md, "| :- | :--- | :--- | :--- | :--- | :--- |");

    for (i, pair) in pairs.iter().enumerate() {
        let src_display = format_validator_display(&pair.source_pubkey, pair.source_index);
        let tgt_display = format_validator_display(&pair.target_pubkey, pair.target_index);
        let tx_display = format_tx_hash_short(pair.el_tx_hash.as_deref());
        let status_badge = status_badge_markdown(pair.status);

        let _ = writeln!(
            md,
            "| {} | {} | {} | {} | {} | {} |",
            i + 1,
            src_display,
            tgt_display,
            tx_display,
            status_badge,
            pair.details
        );
    }
}

// -----------------------------------------------------------------------------
// Helper Formatters
// -----------------------------------------------------------------------------

/// Formats validator public key and optional index safely without out-of-bounds panics.
fn format_validator_display(pubkey: &str, index: Option<u64>) -> String {
    let prefix_len = pubkey.len().min(10);
    let short_key = &pubkey[..prefix_len];

    match index {
        Some(idx) => format!("Index `{}` (`{}...`)", idx, short_key),
        None => format!("`{}...`", short_key),
    }
}

/// Formats a transaction hash into a shortened 0x1234...5678 format safely.
fn format_tx_hash_short(tx_hash: Option<&str>) -> String {
    match tx_hash {
        Some(h) if h.len() > 14 => format!("`{}...{}`", &h[..8], &h[h.len() - 6..]),
        Some(h) => format!("`{}`", h),
        None => "N/A".to_string(),
    }
}

/// Returns a Markdown badge for a given consolidation status.
fn status_badge_markdown(status: ConsolidationStatus) -> &'static str {
    match status {
        ConsolidationStatus::Accepted => "✅ **ACCEPTED**",
        ConsolidationStatus::Queued => "⏳ **QUEUED**",
        ConsolidationStatus::NotAccepted => "❌ **NOT_ACCEPTED**",
        ConsolidationStatus::Indeterminate => "❓ **INDETERMINATE**",
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::models::{LidoFeeExemptionReport, VerificationSummary};
    use chrono::Utc;

    #[test]
    fn test_generate_markdown_receipt() {
        let receipt = VerificationReceipt {
            tool_version: "0.1.0".to_string(),
            timestamp: Utc::now(),
            el_rpc_url: "http://localhost:8545".to_string(),
            cl_beacon_url: "http://localhost:5052".to_string(),
            summary: VerificationSummary {
                total_pairs: 1,
                accepted: 1,
                ..Default::default()
            },
            fee_exemption: LidoFeeExemptionReport {
                st_vault_dashboard: None,
                operator_address: None,
                role_hash: "0x123".to_string(),
                role_active: Some(false),
                fee_exemption_observed: true,
                notes: "Clean".to_string(),
            },
            pairs: vec![PairVerificationResult {
                source_pubkey: "0x0102030405060708090a".to_string(),
                source_index: Some(123),
                target_pubkey: "0x0a090807060504030201".to_string(),
                target_index: Some(456),
                el_tx_hash: Some("0x11223344556677889900aabbccddeeff".to_string()),
                el_block_number: Some(100),
                el_predeploy_found: true,
                beacon_slot: Some(200),
                beacon_request_found: true,
                cl_pending_found: true,
                status: ConsolidationStatus::Accepted,
                details: "Verified in queue".to_string(),
                indeterminate_reason: None,
            }],
        };

        let md = generate_markdown_receipt(&receipt);
        assert!(md.contains("# Lido stVault Consolidation Request Receipt"));
        assert!(md.contains("**STATUS: ALL CONSOLIDATION REQUESTS ACCEPTED**"));
        assert!(md.contains("Index `123` (`0x01020304...`)"));
        assert!(md.contains("✅ **ACCEPTED**"));
    }
}
